"""add tabels

Revision ID: 0964b03f1f49
Revises: 
Create Date: 2023-02-20 16:15:50.953648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0964b03f1f49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_student_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_student_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_student_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_student_email'), type_='unique')

    # ### end Alembic commands ###
