"""empty message

Revision ID: 350221f4f370
Revises: 0964b03f1f49
Create Date: 2023-02-22 12:16:30.023609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350221f4f370'
down_revision = '0964b03f1f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('supject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_student_email'),
    sa.UniqueConstraint('username', name='uq_student_username')
    )
    # ### end Alembic commands ###
